---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-secret
  namespace: threads-dev
spec:
  encryptedData:
    DB_PASSWORD: AgAHyS252BwoFrBU2pSvm7mZ3JCNY7J5j/egVjKfNRsLGjUS4GlD73EcB9t/IWZQCc38KZz3nywHECy3pd8cPy3XqGrcHWPHj/dxL9ZR9zNWem4ab/hc+xM+JHfAfH0U1d8Qs/njLZP3Ol8S+UxZtFUoNoU/esP4GiJ7VK6PL7kit7n3uJ+9eafCw+0PoZsg/kKoPPovlenHym15fvEHnfSOTCJoFPxyGhToHtAEMVEf4MPM0ueoGldX2MVhh0ftYjdJBY4urReyco275kT6QW8ztuXd2MuBOW7GRt0FEUBJrOuMIIXyzwWMvyWMjdAeTk5uIx8HHjNXE2eD/8ZU5kFQJUWISrlhL8XI5LvocA/8EIlSHuVWaClJme6hEG+FxdcLVhNwyz7F00/OYFrv1Fm9IYkDxre0AVtpo5agrRIauaphmpc/rCox2dqfchAtINMKseYKa3S9NV8eNx7HfGfwStMbwWmrJIndI5Ni8E5YZVKj361BZ0aN0dcAXK1U/Q0lK8dGXfgXzuBcmApHIqY7g6Zya3am27I4RNAyiESfxwrgcPYXx1mDWu16K/qRuw7iuL8f8PMeIO4tG5bCwFA5z9WBostpG/LfUsae+hW5/mbaZAWlDMhtj35dfg7OSPhuW+sgaxJc5WqXARLCrMi14TIW1GRho+c2SFNf3NsCCi/vNmZekWAaE5I6WMpY0375Ry91X+UJDYAvzNvP
    JWT_SECRET: AgBawkibeD8CwxF9qdRxpqnQSMiJKqz/pvCs5+oLOkh4RAJLpbHw0AI1OB4usp178H0I4EaxvF4jIDklWa6GC7K0toCdPkwhFl1JYTSH0XRFDsGS0QSnRJxzo0GzO9PA+tn18GJ+u0/oK+y9t6rTBA8d+diuS065TpwfwEJhIU21hgkta6DxNizTrQ82RxbaCcWuMyGjhpB7zY5u+VK5luQ3iUFAcOyiLIZLHRLrsh3RzDmTLhhnE5Mw22Drh4bCX7XRpumqqLEI5l51bAQtcc/ikJ59ljWpOCoFRL7DY3UyHo9s84Hol4O6/pCZIYdgbmG80L2x3SdLQwLB7noeTA/JiN8kQko4K7+xrWOF6niZEPlt9U6tLtk7GudxSiAYAghSw4BOQKpzotd8BbyVrcTJsP6TmFE4fNVRIg91Q9VT3/Y0z1icq0r/6djsOMR5Q/wNPkzznsAPauLxl0JzdZng8ZyRtyR/agpZLpp3CX3rVkArJ4mCUOYwsS/eFoIyd5B9QBNvnFEA9IDHMwAnGhG+vh0WsErqC0QBDy1pe015caKmcn49T6D3w4S6vgYKgHQwZzrbfJd4VWsJy5oLKJHDTGbdDqNTH9RB/KLBjw42PTRFIooQcG93OyDXuqkwkY21Q6x9tIEoXQkkWe1O0T4/CSSxOmDF6xZCPVOIlDwZqE2ZiZtqGdnzbiIh4Q0100I3LiP0SGvibDK+9KlBWRwe7Riv8zw9+94VWyoQV81C0B20rJhFU7EJcKBcPLOpGFFOIu1xm256SVLq4FRdYxSR
  template:
    metadata:
      creationTimestamp: null
      name: api-secret
      namespace: threads-dev
