apiVersion: apps/v1
kind: Deployment
metadata:
  name: threads
spec:
  template:
    spec:
      containers:
        - name: threads
          image: dangnam141002/threads:dev
          env:
            - name: NODE_ENV
              value: development
          ports:
            - containerPort: 80
