apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: threads-dev

resources:
  - ../../../base/postgres

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: postgres
