apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  config.js: |
    window._env_ = {
      VITE_API_URL: "https://threads-api1.namth.online/api",
      VITE_SOCKET_SERVER_URL: "cm_wss://threads-api.namth.online:3001"
    };
