apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  NODE_ENV: "development"
  VITE_API_URL: "https://threads-api.namth.online/api"
  VITE_SOCKET_SERVER_URL: "ws://threads-api.namth.online:3001"
