apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: threads-dev
resources:
  - ../../../base/api

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: api
