apiVersion: apps/v1
kind: Deployment
metadata:
  name: threads
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threads
  template:
    metadata:
      labels:
        app: threads
    spec:
      containers:
        - name: threads
          image: dangnam141002/threads:dev
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "development"
            - name: VITE_API_URL
              value: "http://localhost:3000/api" # ví dụ env cho FE gọi BE
            - name: VITE_SOCKET_SERVER_URL
              value: "http://localhost:4000" # ví dụ env cho FE gọi BE